#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
12_punctuate.py — Apply hanja.dev model to 백문 letters → 표점 letters.

Step 12 of the Phase 0 data preprocessing pipeline.

11_crawl_itkc.py 가 산출한 letters.jsonl 의 plain_text(백문) 필드를
SikuRoBERTa-PUNC-AJD-KLC 모델에 통과시켜, 모델이 부여한 표점 텍스트를
새 필드(punctuated_text)로 추가한 jsonl 을 산출.

WHY hanja.dev 일괄적용
======================

  한국문집총간 정본의 표점은 보존하되 사용하지 않는다.
    - 전통식 표점으로 쉼표 자리에도 。 를 찍어 평균 문장 길이 6자.
    - "處世之難。" 등 의미 단위 분절로 부적합.
    - 주자어류 corpus 와 표점 부여 규칙을 일원화하기 위해 일괄적용.

  원본 표점은 letters.jsonl 의 raw_text 필드에 그대로 보존되며,
  본 스크립트의 출력에도 그대로 유지됨 (hanja.dev 결과와 별도 컬럼).


USAGE
=====

  # 전체 letter 처리 (퇴계 22편 + 율곡 9편)
  python3 scripts/12_punctuate.py

  # 처음 1편만 (sanity check 용)
  python3 scripts/12_punctuate.py --limit 1

  # 모델 revision 고정 (재현성)
  python3 scripts/12_punctuate.py --revision <commit_hash>


OUTPUTS
=======

  data/processed/letters_punctuated.jsonl       letter당 한 줄
  docs/letter_punctuation_provenance.md         실행 메타데이터


SCHEMA (출력 jsonl 한 줄)
=========================

  letters.jsonl 의 모든 필드 +
    - punctuated_text   : 모델이 표점 부여한 텍스트
    - input_text        : 모델에 넣은 입력 (= plain_text, 캐시 검증용)
    - model_id          : HuggingFace 모델 ID
    - model_revision    : 모델 revision (없으면 null)
    - n_chunks          : 청킹된 조각 수
    - timestamp         : 추론 시각 (ISO, UTC)
    - input_hash        : SHA256(model_id + revision + input_text)[:16]
    - text_id           : data_id 와 동일 (PunctuationResult 메타)


DEPENDENCIES
============

  Python ≥ 3.10
  + torch, transformers, huggingface_hub
  + common.punctuate_hanja (이 레포)
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

# common 모듈 import 보장 (어디서 실행해도 동작)
DEFAULT_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(DEFAULT_REPO_ROOT))

from common.punctuate_hanja import (  # noqa: E402
    DEFAULT_MODEL_ID,
    HanjaPunctuator,
)


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------

def punctuate_letters(
    input_path: Path,
    output_path: Path,
    pun: HanjaPunctuator,
    limit: int | None = None,
) -> dict:
    """letters.jsonl → letters_punctuated.jsonl, 통계 반환."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    n_total = 0
    total_input_chars = 0
    total_output_chars = 0

    with input_path.open(encoding="utf-8") as f_in, \
         output_path.open("w", encoding="utf-8") as f_out:
        for line in f_in:
            line = line.strip()
            if not line:
                continue
            if limit is not None and n_total >= limit:
                break

            rec = json.loads(line)
            text = rec["plain_text"]      # 백문 (모델 input)
            text_id = rec["data_id"]      # ITKC ID

            result = pun.punctuate(text, text_id, use_cache=True)

            # 입력 letter + 표점 결과 머지.
            # input_text(=plain_text 사본)와 punctuated_text 가 추가됨.
            # 원본 raw_text(표점 있는 한국문집총간 텍스트)는 유지.
            out_rec = {**rec, **asdict(result)}
            f_out.write(json.dumps(out_rec, ensure_ascii=False) + "\n")

            n_total += 1
            total_input_chars += len(text)
            total_output_chars += len(result.punctuated_text)

            logging.info(
                "  ✓ %s — %s — %d자 → %d자 (chunks=%d)",
                text_id,
                rec.get("title", ""),
                len(text),
                len(result.punctuated_text),
                result.n_chunks,
            )

    return {
        "n_total": n_total,
        "total_input_chars": total_input_chars,
        "total_output_chars": total_output_chars,
    }


# ---------------------------------------------------------------------------
# Provenance
# ---------------------------------------------------------------------------

def write_provenance_md(
    path: Path,
    stats: dict,
    model_id: str,
    revision: str | None,
    device: str,
    started_at: str,
    finished_at: str,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    added_chars = stats["total_output_chars"] - stats["total_input_chars"]
    lines = [
        "# Letter punctuation — provenance",
        "",
        f"Auto-generated by `scripts/12_punctuate.py` at `{finished_at}`.",
        "",
        "이 파일은 매 실행 시 덮어씁니다. 수동 편집 금지.",
        "",
        "## Model",
        "",
        f"- Model ID    : `{model_id}`",
        f"- Revision    : `{revision or '(latest — unpinned)'}`",
        f"- Device      : `{device}`",
        "- Architecture: BertForTokenClassification (NER 스타일 토큰 분류)",
        "- 표점 체계  : 한국고전번역원 (AJD/KLC)",
        "",
        "## Stats",
        "",
        f"- Letters processed     : {stats['n_total']}",
        f"- 입력 백문 총 글자수   : {stats['total_input_chars']:,}",
        f"- 출력 표점 총 글자수   : {stats['total_output_chars']:,}",
        f"- 표점 추가 글자 수     : {added_chars:,}"
        f" ({added_chars / max(stats['total_input_chars'], 1) * 100:.1f}%)",
        "",
        "## Run",
        "",
        f"- Started : {started_at}",
        f"- Finished: {finished_at}",
        "",
    ]
    if revision is None:
        lines += [
            "## ⚠ Reproducibility note",
            "",
            "Revision 이 pinned 되지 않음. 정확한 재현을 위해서는 모델 커밋",
            "해시를 고정해 `--revision <hash>` 로 실행하는 것을 권장.",
            "",
        ]
    path.write_text("\n".join(lines), encoding="utf-8")
    logging.info("Wrote provenance log → %s", path)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--repo-root", type=Path, default=DEFAULT_REPO_ROOT)
    ap.add_argument("--input", type=Path, default=None,
                    help="입력 jsonl (default: <repo>/data/raw/letters.jsonl)")
    ap.add_argument("--output", type=Path, default=None,
                    help="출력 jsonl (default: <repo>/data/processed/letters_punctuated.jsonl)")
    ap.add_argument("--model", default=DEFAULT_MODEL_ID,
                    help="HuggingFace 모델 ID (default: %(default)s)")
    ap.add_argument("--revision", default=None,
                    help="모델 revision — 커밋 해시 권장")
    ap.add_argument("--device", default=None,
                    help="cpu / cuda / mps (default: 자동)")
    ap.add_argument("--limit", type=int, default=None,
                    help="처음 N편만 처리 (테스트용)")
    ap.add_argument("--debug", action="store_true")
    args = ap.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.debug else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )

    repo_root = args.repo_root.resolve()
    input_path = (args.input or (repo_root / "data/raw/letters.jsonl")).resolve()
    output_path = (args.output or
                   (repo_root / "data/processed/letters_punctuated.jsonl")).resolve()

    if not input_path.exists():
        sys.exit(
            f"입력 파일 없음: {input_path}\n"
            "먼저 `python3 scripts/11_crawl_itkc.py` 실행 필요."
        )

    started_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    logging.info("=== 12_punctuate.py ===")
    logging.info("Input : %s", input_path)
    logging.info("Output: %s", output_path)
    logging.info("Model : %s (revision=%s)", args.model, args.revision)

    pun = HanjaPunctuator(
        model_id=args.model,
        revision=args.revision,
        device=args.device,
    )

    if args.limit:
        logging.info("Limit set: 처음 %d편만 처리", args.limit)

    stats = punctuate_letters(input_path, output_path, pun, limit=args.limit)
    finished_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    write_provenance_md(
        repo_root / "docs/letter_punctuation_provenance.md",
        stats,
        args.model,
        args.revision,
        pun.device,
        started_at,
        finished_at,
    )

    logging.info(
        "Done. %d letters, %s자 (백문) → %s자 (표점, +%s자)",
        stats["n_total"],
        f"{stats['total_input_chars']:,}",
        f"{stats['total_output_chars']:,}",
        f"{stats['total_output_chars'] - stats['total_input_chars']:,}",
    )


if __name__ == "__main__":
    main()
